# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=64)),
                ('lname', models.CharField(max_length=64)),
                ('descr', models.CharField(default='', max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('publisher', models.CharField(max_length=256)),
                ('year', models.CharField(max_length=4)),
                ('descr', models.CharField(default='', max_length=512)),
                ('author', models.ManyToManyField(related_name='author', to='berkeley.Person')),
                ('editor', models.ManyToManyField(related_name='editor', to='berkeley.Person')),
                ('translator', models.ManyToManyField(related_name='translator', to='berkeley.Person')),
            ],
        ),
    ]
