# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-07 05:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(default='', max_length=64)),
                ('mname', models.CharField(blank=True, default='', max_length=64)),
                ('lname', models.CharField(max_length=64)),
                ('descr', models.CharField(blank=True, default='', max_length=512)),
                ('yob', models.CharField(blank=True, default='', max_length=4)),
                ('yod', models.CharField(blank=True, default='', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('year', models.CharField(max_length=4)),
                ('edition', models.CharField(blank=True, default='', max_length=4)),
                ('city', models.CharField(blank=True, default='', max_length=128)),
                ('isbn', models.CharField(blank=True, default='', max_length=24, null=True)),
                ('sn', models.CharField(blank=True, default='', max_length=12, null=True)),
                ('language', models.CharField(blank=True, default='', max_length=32)),
                ('abstract', models.CharField(blank=True, default='', max_length=1024)),
                ('url', models.CharField(blank=True, default='', max_length=512)),
                ('authors', models.ManyToManyField(related_name='authors', to='berkeley.Person')),
                ('editors', models.ManyToManyField(blank=True, default='', related_name='editors', to='berkeley.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('city', models.CharField(default='', max_length=128)),
                ('province', models.CharField(blank=True, default='', max_length=128)),
                ('country', models.CharField(default='', max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='publication',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='berkeley.Publisher'),
        ),
        migrations.AddField(
            model_name='publication',
            name='translator',
            field=models.ManyToManyField(blank=True, default='', related_name='translator', to='berkeley.Person'),
        ),
    ]
