# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 05:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('berkeley', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('city', models.CharField(default='', max_length=128)),
                ('province', models.CharField(default='', max_length=128)),
                ('country', models.CharField(default='', max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='yob',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AddField(
            model_name='person',
            name='yod',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AddField(
            model_name='publication',
            name='city',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='publication',
            name='edition',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AddField(
            model_name='publication',
            name='isbn',
            field=models.CharField(default='', max_length=24),
        ),
        migrations.AlterField(
            model_name='person',
            name='fname',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='publication',
            name='author',
            field=models.ManyToManyField(default='', related_name='author', to='berkeley.Person'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='editor',
            field=models.ManyToManyField(default='', related_name='editor', to='berkeley.Person'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='berkeley.Publisher'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='translator',
            field=models.ManyToManyField(default='', related_name='translator', to='berkeley.Person'),
        ),
    ]
