# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berkeley', '0002_auto_20160202_0507'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='language',
            field=models.CharField(default='', max_length=32),
        ),
    ]
