# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berkeley', '0003_publication_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='mname',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='person',
            name='descr',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='person',
            name='yob',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='person',
            name='yod',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='publication',
            name='city',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='publication',
            name='descr',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='publication',
            name='edition',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='publication',
            name='editor',
            field=models.ManyToManyField(blank=True, default='', related_name='editor', to='berkeley.Person'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='language',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='publication',
            name='translator',
            field=models.ManyToManyField(blank=True, default='', related_name='translator', to='berkeley.Person'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='province',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
