# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 07:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('berkeley', '0004_auto_20160203_0703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='editor',
        ),
        migrations.AddField(
            model_name='publication',
            name='editor',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='editor', to='berkeley.Person'),
        ),
        migrations.RemoveField(
            model_name='publication',
            name='translator',
        ),
        migrations.AddField(
            model_name='publication',
            name='translator',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='translator', to='berkeley.Person'),
        ),
    ]
