# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berkeley', '0005_auto_20160203_0713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='editor',
        ),
        migrations.AddField(
            model_name='publication',
            name='editor',
            field=models.ManyToManyField(blank=True, default='', null=True, related_name='editor', to='berkeley.Person'),
        ),
        migrations.RemoveField(
            model_name='publication',
            name='translator',
        ),
        migrations.AddField(
            model_name='publication',
            name='translator',
            field=models.ManyToManyField(blank=True, default='', null=True, related_name='translator', to='berkeley.Person'),
        ),
    ]
