# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 07:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('berkeley', '0006_auto_20160203_0749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='translator',
        ),
    ]
