# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 07:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('berkeley', '0007_auto_20160203_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='ed',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ed', to='berkeley.Person'),
        ),
        migrations.AddField(
            model_name='publication',
            name='trans',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trans', to='berkeley.Person'),
        ),
    ]
