# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 07:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('berkeley', '0008_auto_20160203_0751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='author',
        ),
        migrations.AddField(
            model_name='publication',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='author', to='berkeley.Person'),
        ),
    ]
