# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 08:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('berkeley', '0009_auto_20160203_0755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='author',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='ed',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='trans',
        ),
        migrations.AddField(
            model_name='publication',
            name='editor',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='editor', to='berkeley.Person'),
        ),
        migrations.AddField(
            model_name='publication',
            name='prim_author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='prim_author', to='berkeley.Person'),
        ),
        migrations.AddField(
            model_name='publication',
            name='translator',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translator', to='berkeley.Person'),
        ),
    ]
